# Generated by Django 5.2.7 on 2025-11-26 21:50

import colorfield.fields
import db.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True, unique=True, verbose_name='Nombre')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color de Identificación')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre')),
                ('tipoPersona', models.CharField(max_length=1, null=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', db.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApartadoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeSeccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=3)),
                ('clave', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'unique_together': {('tipoDeSeccion', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.estado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.socio')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionesExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeSeccion', models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Informacion Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Información de garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento')], max_length=3)),
                ('tituloSeccion', models.CharField(blank=True, max_length=100, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.apartadocatalogo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.seccionesexpediente')),
            ],
            options={
                'unique_together': {('seccion', 'apartado')},
            },
        ),
    ]
