# Generated by Django 5.2.7 on 2025-11-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartadob',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='apartadoc',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='apartadod',
            name='expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='comentarios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFilaExcel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('textoFilaExcel', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.apartado')),
            ],
        ),
        migrations.DeleteModel(
            name='ApartadoA',
        ),
        migrations.DeleteModel(
            name='ApartadoB',
        ),
        migrations.DeleteModel(
            name='ApartadoC',
        ),
        migrations.DeleteModel(
            name='ApartadoD',
        ),
    ]
