# Generated by Django 6.0 on 2026-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numeroKepler',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Numero en Kepler'),
        ),
    ]
