# Generated by Django 5.2.7 on 2025-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Ejecutivo de Negocios', 'Ejecutivo de Negocios'), ('Ejecutivo de servicios', 'Ejecutivo de servicios'), ('Administrador', 'Administrador'), ('Credito', 'Credito'), ('Juridico', 'Juridico'), ('Visitante', 'Visitante')], default='Visitante', max_length=30, null=True),
        ),
    ]
