# Generated by Django 5.2.7 on 2025-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartadocatalogo',
            name='areaDondeAplica',
            field=models.CharField(blank=True, choices=[('Fisicas', 'Fisicas'), ('Ambas', 'Ambas'), ('Morales', 'Morales')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Habilitar Usuario'),
        ),
    ]
