# Generated by Django 5.2.7 on 2025-11-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_apartadob_expediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosexcel',
            name='apartado',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Apartado',
        ),
        migrations.DeleteModel(
            name='RegistrosExcel',
        ),
    ]
