# Generated by Django 6.0 on 2026-01-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_socio_numerokepler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='socio',
        ),
        migrations.AddField(
            model_name='linea',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.expediente'),
        ),
    ]
