# Generated by Django 5.2.7 on 2025-11-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_estado_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='date',
            new_name='fecha',
        ),
    ]
