# Generated by Django 5.2.7 on 2025-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_apartadocatalogo_areadondeaplica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartadocatalogo',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=7),
        ),
    ]
