# Generated by Django 6.0 on 2026-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_expediente_linea_remove_expediente_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
