# Generated by Django 5.2.7 on 2025-11-24 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_registrosexcel_apartado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionesExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeSeccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('tituloSeccion', models.CharField(blank=True, max_length=100, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.DecimalField(decimal_places=2, max_digits=5)),
                ('texto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('comentarios', models.CharField(max_length=255)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.seccionesexpediente')),
            ],
        ),
    ]
