# Generated by Django 5.2.7 on 2025-11-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_seccionesexpediente_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('D', 'Actividades vulnerables')], max_length=1),
        ),
        migrations.CreateModel(
            name='ApartadoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeSeccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('clave', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'unique_together': {('tipoDeSeccion', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='RegistroSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.apartadocatalogo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.seccionesexpediente')),
            ],
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
