# Generated by Django 5.2.7 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_apartadocatalogo_tipodeseccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Nuevo', max_length=20, unique=True, verbose_name='Usuario'),
        ),
    ]
