# Generated by Django 6.0 on 2026-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_linea_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='tipoLinea',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Back', 'Back')], default='Libre'),
        ),
    ]
