# Generated by Django 6.0 on 2026-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_linea_tipolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Numero'),
        ),
    ]
