# Generated by Django 6.0 on 2026-01-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='is_obligado',
            field=models.BooleanField(default=False, verbose_name='Obligado Solidario'),
        ),
        migrations.AddField(
            model_name='socio',
            name='is_representante',
            field=models.BooleanField(default=False, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='socio',
            name='is_socio',
            field=models.BooleanField(default=True, verbose_name='Socio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Ejecutivo de Negocios', 'Ejecutivo de Negocios'), ('Ejecutivo de Servicios', 'Ejecutivo de Servicios'), ('Administrador', 'Administrador'), ('Credito', 'Credito'), ('Juridico', 'Juridico'), ('Visitante', 'Visitante')], default='Visitante', max_length=30, null=True),
        ),
    ]
