# Generated by Django 5.2.7 on 2025-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_seccionesexpediente_tipodeseccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartadocatalogo',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Informacion Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Información de garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento')], max_length=3),
        ),
    ]
