# Generated by Django 6.0 on 2026-01-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_linea_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='numero',
            field=models.CharField(default=2, max_length=10, unique=True, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
