# Generated by Django 5.2.7 on 2025-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_apartadocatalogo_tipodeseccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
