# Generated by Django 5.2.7 on 2025-11-25 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_expediente_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='anio_fijo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroseccion',
            name='fecha_fija',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroseccion',
            name='mes_fijo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
