# Generated by Django 6.0 on 2026-02-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_linea_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligadosolidario',
            name='expedientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Expedientes_Obligados', to='db.expediente'),
        ),
        migrations.AddField(
            model_name='representantelegal',
            name='expedientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Expedientes_Representantes', to='db.expediente'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.expediente'),
        ),
    ]
