# Generated by Django 6.0 on 2026-02-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_obligadosolidario_expedientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='is_obligado',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='is_representante',
        ),
    ]
