# Generated by Django 5.2.7 on 2025-11-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_registroseccion_anio_fijo_registroseccion_fecha_fija_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroseccion',
            name='anio_fijo',
        ),
        migrations.RemoveField(
            model_name='registroseccion',
            name='fecha_fija',
        ),
        migrations.RemoveField(
            model_name='registroseccion',
            name='mes_fijo',
        ),
    ]
