# Generated by Django 6.0 on 2026-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_socio_is_obligado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Ejecutivo de Negocios', 'Ejecutivo de Negocios'), ('Ejecutivo de Servicios', 'Ejecutivo de Servicios'), ('Administrador', 'Administrador'), ('Credito', 'Credito'), ('Gerente', 'Gerente')], default='Administrador', max_length=30, null=True),
        ),
    ]
