# Generated by Django 5.2.7 on 2025-11-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_registroseccion_anio_fijo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado')},
        ),
    ]
