# Generated by Django 6.0 on 2026-05-19 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuarioCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroNegocios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Ejecutivo de Negocios', 'Ejecutivo de Negocios'), ('Ejecutivo de Servicios', 'Ejecutivo de Servicios'), ('Administrador', 'Administrador'), ('Credito', 'Credito'), ('Gerente de Credito', 'Gerente de Credito'), ('Gerente Centro de Negocios', 'Gerente Centro de Negocios')], default='Administrador', max_length=30, null=True),
        ),
    ]
