# Generated by Django 5.2.7 on 2025-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_registroseccion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='idKepler',
            field=models.CharField(max_length=4, null=True, verbose_name='KeplerID'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipoPersona',
            field=models.CharField(max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
