# Generated by Django 6.0 on 2026-05-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_expediente_usuariocredito_alter_expediente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuarioArchivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Archivado', to=settings.AUTH_USER_MODEL),
        ),
    ]
