# Generated by Django 6.0 on 2026-05-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_expediente_usuarioarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombreCompleto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NombreCompleto'),
        ),
    ]
