# Generated by Django 6.0 on 2026-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_user_nombrecompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='comentarioCredito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('expedientes', models.ManyToManyField(blank=True, null=True, related_name='Expedientes_Citas', to='db.expediente')),
            ],
        ),
    ]
