# Generated by Django 6.0 on 2026-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_cambiosestados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='tipoLinea',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Back', 'Back'), ('Hipotecaria', 'Hipotecaria'), ('Fidusiaria', 'Fidusiaria')], default='Libre'),
        ),
    ]
