# Generated by Django 6.0 on 2026-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_estado_nombre_alter_linea_tipolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Hipotecaria', 'Hipotecaria'), ('Prendaria', 'Prendaria'), ('Colateral', 'Colateral'), ('Avales', 'Avales'), ('Fiduciaria', 'Fiduciaria'), ('Sin garantia', 'Sin garantia')], default='Cuenta Corriente', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='linea',
            name='tipoLinea',
            field=models.CharField(choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Simple', 'Simple'), ('Habilitacion', 'Habilitacion'), ('Refaccionario', 'Refaccionario'), ('Factoraje', 'Factoraje'), ('Quirografario', 'Quirografario'), ('Linea de descuento', 'Linea de descuento')], default='Cuenta Corriente', max_length=50),
        ),
        migrations.AddField(
            model_name='linea',
            name='tipoGarantia',
            field=models.ManyToManyField(blank=True, related_name='lineas', to='db.garantia'),
        ),
    ]
