# Generated by Django 6.0 on 2026-06-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_garantia_alter_linea_tipolinea_linea_tipogarantia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='fecha',
            new_name='fechaCreacion',
        ),
    ]
