# Generated by Django 6.0 on 2026-06-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_rename_fecha_expediente_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.estado')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.expediente')),
            ],
        ),
    ]
