# Generated by Django 6.0 on 2026-06-01 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_estadosfechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosfechas',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estadosfechas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CambiosEstados',
        ),
    ]
