# Generated by Django 6.0 on 2026-06-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_estadosfechas_hora_estadosfechas_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuarioNegocios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL),
        ),
    ]
