# Generated by Django 6.0 on 2026-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
