# Generated by Django 6.0 on 2026-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_cita_rechazada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='rechazada',
        ),
        migrations.AddField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Pendiente'),
        ),
    ]
