# Generated by Django 6.0 on 2026-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_remove_cita_rechazada_cita_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='estatus',
            new_name='estatusCN',
        ),
        migrations.AddField(
            model_name='cita',
            name='estatusCR',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Pendiente'),
        ),
    ]
