# Generated by Django 6.0 on 2026-06-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_rename_estatus_cita_estatuscn_cita_estatuscr'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='es_fecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registroseccion',
            name='numero',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='expedientes',
            field=models.ManyToManyField(related_name='Expedientes_Citas', to='db.expediente'),
        ),
        migrations.AlterField(
            model_name='obligadosolidario',
            name='expedientes',
            field=models.ManyToManyField(related_name='Expedientes_Obligados', to='db.expediente'),
        ),
        migrations.AlterField(
            model_name='representantelegal',
            name='expedientes',
            field=models.ManyToManyField(related_name='Expedientes_Representantes', to='db.expediente'),
        ),
    ]
