# Generated by Django 6.0 on 2026-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_registroseccion_es_fecha_registroseccion_numero_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registroseccion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
