# Generated by Django 6.0 on 2026-06-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_registroseccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado')},
        ),
    ]
