# Generated by Django 6.0 on 2026-06-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_alter_registroseccion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together=set(),
        ),
    ]
