# Generated by Django 6.0 on 2026-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_alter_registroseccion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='secuencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado', 'secuencia')},
        ),
    ]
