# Generated by Django 6.0 on 2026-06-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_registroseccion_secuencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado')},
        ),
        migrations.RemoveField(
            model_name='registroseccion',
            name='secuencia',
        ),
    ]
