# Generated by Django 6.0 on 2026-06-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_alter_registroseccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='secuencial',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
