# Generated by Django 6.0 on 2026-06-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_registroseccion_secuencial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado', 'secuencial')},
        ),
    ]
