# Generated by Django 6.0 on 2026-06-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_alter_registroseccion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroseccion',
            unique_together={('seccion', 'apartado', 'secuencial')},
        ),
    ]
