# Generated by Django 6.0 on 2026-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_alter_registroseccion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
    ]
