# Generated by Django 6.0 on 2026-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_alter_linea_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroseccion',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
