# Generated by Django 6.0 on 2026-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_alter_registroseccion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartadocatalogo',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=7),
        ),
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Informacion Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Información de garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento'), ('VII', 'Correspondencia')], max_length=3),
        ),
    ]
