# Generated by Django 6.0 on 2026-06-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_seccionesexpediente_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroseccion',
            name='apartado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.apartadocatalogo'),
        ),
    ]
