# Generated by Django 6.0 on 2026-06-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_alter_registroseccion_apartado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligadosolidario',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.representantelegal'),
        ),
    ]
