# Generated by Django 6.0 on 2026-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_obligadosolidario_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='enviar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linea',
            name='tipoLinea',
            field=models.CharField(choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Simple', 'Simple'), ('Habilitacion', 'Habilitacion'), ('Refaccionario', 'Refaccionario'), ('Factoraje', 'Factoraje'), ('Quirografario', 'Quirografario'), ('Linea de descuento', 'Linea de descuento'), ('Arrendamiento Puro', 'Arrendamiento Puro'), ('Arrendamietn Financiero', 'Arrendamietn Financiero')], default='Cuenta Corriente', max_length=50),
        ),
    ]
