# Generated by Django 6.0 on 2026-06-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_registroseccion_enviar_alter_linea_tipolinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroseccion',
            name='enviar',
        ),
    ]
