# Generated by Django 6.0 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_remove_registroseccion_enviar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroseccion',
            name='enviar',
            field=models.BooleanField(default=False),
        ),
    ]
