# Generated by Django 6.0 on 2026-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_registroseccion_enviar'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
