# Generated by Django 6.0 on 2026-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_estado_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
