# Generated by Django 6.0 on 2026-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_linea_abreviacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
