# Generated by Django 6.0 on 2026-07-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_linea_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.socio', unique=True),
        ),
    ]
