# Generated by Django 6.0 on 2026-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_alter_expediente_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='descripcion'),
        ),
    ]
