# Generated by Django 6.0 on 2026-07-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_estado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fechaArchivado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
