# Generated by Django 6.0 on 2026-07-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_expediente_fechaarchivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.socio'),
        ),
    ]
