# Generated by Django 6.0 on 2026-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0051_alter_expediente_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartadocatalogo',
            name='nombreArchivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
    ]
