# Generated by Django 6.0 on 2026-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_apartadocatalogo_nombrearchivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='expedienteResagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Informacion Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Informacion de garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento'), ('VII', 'Correspondencia')], max_length=3),
        ),
    ]
