# Generated by Django 6.0 on 2026-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_expediente_expedienteresagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Información Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Información de garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento'), ('VII', 'Correspondencia')], max_length=3),
        ),
    ]
