# Generated by Django 6.0 on 2026-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_alter_seccionesexpediente_tipodeseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='contemplado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seccionesexpediente',
            name='tipoDeSeccion',
            field=models.CharField(choices=[('A', 'Solicitante'), ('B', 'Representante legal'), ('C', 'Obligado solidario y garantes'), ('I', 'Actividades vulnerables'), ('II', 'Información Financiera'), ('III', 'Estudio de Crédito'), ('IV', 'Información de Garantias'), ('V', 'Contratos'), ('VI', 'Seguimiento'), ('VII', 'Correspondencia')], max_length=3),
        ),
    ]
