# Generated by Django 6.0 on 2026-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_expediente_contemplado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligadosolidario',
            name='expedientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Expedientes_Obligados', to='db.expediente'),
        ),
    ]
