# Generated by Django 6.0 on 2026-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_alter_obligadosolidario_expedientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
